apiVersion: "v1"
kind: "BuildConfig"
metadata:
  name: "flyway-migration"
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/filiples/flyway.git"
  strategy:
    dockerStrategy:
      dockerfilePath: ./Dockerfile
  postCommit: 
    script: |
      git clone --branch $GIT_BRANCH --single-branch https://$GIT_USERNAME:$GIT_PASSWORD@$GIT_REPO $HOME/flyway-repo
      cp -f $HOME/flyway-repo/src/main/resources/sql/* $FLYWAY_HOME/sql
      $FLYWAY_HOME/flyway clean migrate -user=$DB_USER -password=$DB_PASS -url=$DB_URL
